/**********************************************************************
* © 2005 Microchip Technology Inc.
*
* Modified by Henryk Paluch for dsPIC33FJ128MC802 
* running on Microstick II board.
* 
* FileName:        main.c
* Dependencies:    Header (.h) files if applicable, see below
* Processor:       dsPIC33Fxxxx/PIC24Hxxxx
* Compiler:        XC16 v1.70
* IDE:             MPLAB X IDE v5.45
* DFP:             dsPIC33F-GP-MC_DFP 1.3.64
* Tested On:	   dsPIC33FJ128MC802 Microstick II board
* Functions:
* - Blinking LED on RA0 PIN 2 at frequency F_cy / 10,000,000 => ~ 4Hz
* - f_cy / 1000 output on RA1 PIN 3 => 40 kHz
* 
* SOFTWARE LICENSE AGREEMENT:
* Microchip Technology Incorporated ("Microchip") retains all ownership and 
* intellectual property rights in the code accompanying this message and in all 
* derivatives hereto.  You may use this code, and any derivatives created by 
* any person or entity by or on your behalf, exclusively with Microchip's
* proprietary products.  Your acceptance and/or use of this code constitutes 
* agreement to the terms and conditions of this notice.
*
* CODE ACCOMPANYING THIS MESSAGE IS SUPPLIED BY MICROCHIP "AS IS".  NO 
* WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED 
* TO, IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A 
* PARTICULAR PURPOSE APPLY TO THIS CODE, ITS INTERACTION WITH MICROCHIP'S 
* PRODUCTS, COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
*
* YOU ACKNOWLEDGE AND AGREE THAT, IN NO EVENT, SHALL MICROCHIP BE LIABLE, WHETHER 
* IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE OR BREACH OF STATUTORY DUTY), 
* STRICT LIABILITY, INDEMNITY, CONTRIBUTION, OR OTHERWISE, FOR ANY INDIRECT, SPECIAL, 
* PUNITIVE, EXEMPLARY, INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, FOR COST OR EXPENSE OF 
* ANY KIND WHATSOEVER RELATED TO THE CODE, HOWSOEVER CAUSED, EVEN IF MICROCHIP HAS BEEN 
* ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT 
* ALLOWABLE BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY RELATED TO 
* THIS CODE, SHALL NOT EXCEED THE PRICE YOU PAID DIRECTLY TO MICROCHIP SPECIFICALLY TO 
* HAVE THIS CODE DEVELOPED.
*
* You agree that you are solely responsible for testing the code and 
* determining its suitability.  Microchip has no obligation to modify, test, 
* certify, or support the code.
*
* REVISION HISTORY:
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* Author            Date      Comments on this revision
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* Abhishek Jain		04/10/2007  
*
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* ADDITIONAL NOTES: 
* The Processor starts with the External Crystal without PLL enabled and then the Clock is switched to PLL Mode.
*
**********************************************************************/
#if defined(__dsPIC33F__)
#include "p33Fxxxx.h"
#elif defined(__PIC24H__)
#include "p24Hxxxx.h"
#endif

// Select internal FRC at POR
_FOSCSEL(FNOSC_FRC);
// Enable clock switching and configure
_FOSC(FCKSM_CSECMD & OSCIOFNC_OFF);

_FWDT(FWDTEN_OFF); 			            			// Watchdog Timer Enabled/disabled by user software

void Init_Timer1( void )
{
    // Timer1 - divides F_clk by 1,000,000 (so F_cy by 500,000)
    //          for F_clk 80MHz -> Interrupt Freq is 80Hz
    // copied from code generated by MCC for dsPIC33EP64MC203
    //TMR1 0; 
    TMR1 = 0x00;
    //Period = 0.125 s; Frequency = 4000000 Hz; PR1 62499; 
    PR1 = 0xF423;
    //TCKPS 1:8; TON enabled; TSIDL disabled; TCS FOSC/2; TSYNC disabled; TGATE disabled; 
    T1CON = 0x8010;
    IFS0bits.T1IF = 0;
    IEC0bits.T1IE = 1;
}

void Init_Timer2( void )
{
    // divide f_clock by 1000 (f_cy by 500)
    // copied from code generated by MCC for dsPIC33EP64MC203

    //TMR2 0; 
    TMR2 = 0x00;
    //Period = 0.000125 s; Frequency = 4000000 Hz; PR2 499; 
    PR2 = 0x1F3;
    //TCKPS 1:1; T32 16 Bit; TON enabled; TSIDL disabled; TCS FOSC/2; TGATE disabled; 
    T2CON = 0x8000;
    IFS0bits.T2IF = 0;
    IEC0bits.T2IE = 1;
}

void __attribute__((interrupt,no_auto_psv)) _T2Interrupt( void )
{
    // Interrupt freq is f_clk / 1000
    // output f_cy / 1000
	LATAbits.LATA1 = ~LATAbits.LATA1;		    
    IFS0bits.T2IF = 0;
}


// NOTE: volatile is absolutely necessary for XC16 v1.70
volatile unsigned int Count;

/* ISR ROUTINE FOR THE TIMER1 INTERRUPT */

void __attribute__((interrupt,no_auto_psv)) _T1Interrupt( void )
{
    Count++; // currently unused
    // RA0 blinks with f_clk / 1,000,000 / 10 / 2
    if (Count == 10){
        Count = 0;
        LATAbits.LATA0 = ~LATAbits.LATA0;
    }
    // must clear interrupt to confirm
    IFS0bits.T1IF = 0;	
}
/*-----------------------*/

int main(void)
{
	
	RCONbits.SWDTEN=0;            /* Disable Watch Dog Timer*/
    
    // attempt to set FRC to expected 7.37MHz
    // my FRC seems to be running on 7.3348 MHz
    OSCTUN = 0x0001;  // got f_cy = 3.6922 MHz => f_frc = 7.3678 MHz
    // NOTE: Your FRC may require different values of OSCTUN!!!

#define USE_FRC_PLL    
#ifdef USE_FRC_PLL    
    // Now switch from FRC f = 7.37Mhz to 80MHz (40MIPS) using PLL
    // From Example 48-2
    //      of http://ww1.microchip.com/downloads/en/DeviceDoc/DS-70596A.pdf
    // Configure PLL prescaler, PLL postscaler, and PLL divisor
    PLLFBD = 41; // M = 43
    CLKDIVbits.PLLPRE=0; // N1 = 2
    CLKDIVbits.PLLPOST=0; // N2 = 2
    // Initiate clock switch to internal FRC with PLL (NOSC = 0b001)
    __builtin_write_OSCCONH(0x01);
    __builtin_write_OSCCONL(0x01);
    // Wait for clock switch to occur
    while (OSCCONbits.COSC != 0b001){/*nop*/};
    // Wait for PLL to lock
    while(OSCCONbits.LOCK!=1){/*nop*/};
    // now we should be running on f = 80MHz, f_cy = 40 MHz (40MIPS)
#endif
    
   /*Initialize the Ports */    
    TRISA = 0x0000;
    LATA  = 0x0000;
    PORTA = 0x0000;

    /*Initialize Timer 1 for Period Interrupts*/

    Init_Timer1();

    Init_Timer2();
	
	while(1)
	{
        asm("NOP");
        asm("NOP");
	}
}
/******************************************************************************/

